# Generated by Django 5.0.7 on 2024-09-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('main', '0002_communitywork_profile_pic_doctor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywork',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.cell'),
        ),
        migrations.AlterField(
            model_name='communitywork',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='communitywork',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.sector'),
        ),
        migrations.AlterField(
            model_name='communitywork',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.village'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.cell'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.sector'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.village'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.cell'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.sector'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.village'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.cell'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.sector'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.village'),
        ),
    ]
