# Generated by Django 5.0.7 on 2024-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_healthfacility_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywork',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
