# Generated by Django 5.0.7 on 2024-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_communitywork_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
