# Generated by Django 5.0.7 on 2024-09-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_visit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.healthfacility'),
        ),
    ]
